### ISSUE TITLE
Furnace Generator doesn't accept items from pipes.

### ISSUE THREAD

**Issue by SlimF** [EpicSquid/GadgetryMachines#2]
I tried inserting items into it with Logistics Pipes, Embers and Gadgetry from all sides but nothing worked.

Edit: Forgot to say that the pipes connect visually to the generator.

Gadgetry Core:  1.0.0
Gadgetry Machines: 1.0.1
Forge: 2772

**Comment by Bluberry-Kat** [comment]
have you changed any of the sides to input with the wrench from gadgetry?

**Comment by SlimF** [comment]
I am an idiot. Thank you !
